{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "dnsmesh.fullname" . }}-config
  labels:
    {{- include "dnsmesh.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.target.name | default .Values.globalConfig.secretName }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
  {{- if .Values.externalSecret.data }}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
  {{- else }}
  data:
    - secretKey: {{ .Values.globalConfig.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        {{- if .Values.externalSecret.remoteRef.property }}
        property: {{ .Values.externalSecret.remoteRef.property }}
        {{- end }}
  {{- end }}
{{- end }}
