apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnsmesh.fullname" . }}
  labels:
    {{- include "dnsmesh.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "dnsmesh.selectorLabels" . | nindent 4 }}
