apiVersion: v2
name: dnsmesh
description: Simple DNS-based service discovery for multi-cluster Kubernetes
type: application
# x-release-please-start-version
version: 0.1.0
# x-release-please-end
# x-release-please-start-version
appVersion: "0.1.0"
# x-release-please-end
keywords:
  - dns
  - service-discovery
  - multi-cluster
  - kubernetes
maintainers:
  - name: tommyskeff
home: https://github.com/tommyskeff/dnsmesh
sources:
  - https://github.com/tommyskeff/dnsmesh
